// constants.js

export const WORKERS = [
  {
    name: "Plan Tose",
    location: "Thrissur",
    rating: 3.8,
    reviews: 520,
    roles: ["Designer", "Architect", "+ 2"],
    description: "I am a professional Architect with 5 years of experience.I am a professional Architect with 5 years of experience",
    price: "899 Rs",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d",
    avatar: "https://randomuser.me/api/portraits/men/18.jpg",
  },
  {
    name: "Plan Tose",
    location: "Thrissur",
    rating: 3.8,
    reviews: 520,
    roles: ["Designer", "Architect", "+ 2"],
    description: "I am a professional Architect with 5 years of experience",
    price: "899 Rs",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d",
    avatar: "https://randomuser.me/api/portraits/men/18.jpg",
  },
  {
    name: "Athul Murali Gangadharann",
    location: "Thrissur",
    rating: 3.8,
    reviews: 520,
    roles: ["Designer", "Architect", "+ 2"],
    description: "I am a professional Architect with 7 years of experience",
    price: "799 Rs",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d",
    avatar: "https://randomuser.me/api/portraits/men/75.jpg",
  },
  {
    name: "Athul Murali",
    location: "Thrissur",
    rating: 3.8,
    reviews: 520,
    roles: ["Designer", "Architect", "+ 2"],
    description: "I am a professional Architect with 7 years of experience",
    price: "799 Rs",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d",
    avatar: "https://randomuser.me/api/portraits/men/75.jpg",
  },
  {
    name: "Athul Murali",
    location: "Thrissur",
    rating: 3.8,
    reviews: 520,
    roles: ["Designer", "Architect", "+ 2"],
    description: "I am a professional Architect with 7 years of experience",
    price: "799 Rs",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d",
    avatar: "https://randomuser.me/api/portraits/men/75.jpg",
  },
  {
    name: "Athul Murali",
    location: "Thrissur",
    rating: 3.8,
    reviews: 520,
    roles: ["Designer", "Architect", "+ 2"],
    description: "I am a professional Architect with 7 years of experience",
    price: "799 Rs",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d",
    avatar: "https://randomuser.me/api/portraits/men/75.jpg",
  },
  {
    name: "Athul Murali",
    location: "Thrissur",
    rating: 3.8,
    reviews: 520,
    roles: ["Designer", "Architect", "+ 2"],
    description: "I am a professional Architect with 7 years of experience",
    price: "799 Rs",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d",
    avatar: "https://randomuser.me/api/portraits/men/75.jpg",
  },
  {
    name: "Athul Murali",
    location: "Thrissur",
    rating: 3.8,
    reviews: 520,
    roles: ["Designer", "Architect", "+ 2"],
    description: "I am a professional Architect with 7 years of experience",
    price: "799 Rs",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d",
    avatar: "https://randomuser.me/api/portraits/men/75.jpg",
  },
  {
    name: "Athul Murali",
    location: "Thrissur",
    rating: 3.8,
    reviews: 520,
    roles: ["Designer", "Architect", "+ 2"],
    description: "I am a professional Architect with 7 years of experience",
    price: "799 Rs",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d",
    avatar: "https://randomuser.me/api/portraits/men/75.jpg",
  },
];
