export const bookingsData = [
  {
    service: "Plumbing",
    date: "Monday, 22 May",
    time: "10:00 – 11:30 AM",
    fullAddress: "Green Villa, P.O Ollur, Thrissur 680306",
    specialInstruction: "Be careful while handling pipes near the water tank.",
    worker: {
      name: "Daison Babu",
      avatar: "https://randomuser.me/api/portraits/men/45.jpg",
      location: "Palakkad",
      phone: "+91 94435 11223",
    },
    status: "in-progress",
  },
  {
    service: "Cleaning",
    date: "Friday, 24 May",
    fullAddress: "Rose Garden Apartments, Chalakudy, Thrissur",
    time: "01:00 – 02:30 PM",
    specialInstruction: "Use eco-friendly cleaning liquids only.",
    worker: {
      name: "Jane Cooper",
      avatar: "https://randomuser.me/api/portraits/women/65.jpg",
      location: "Kollam",
      phone: "+91 98764 22255",
    },
    status: "completed",
  },
  {
    service: "Electrical",
    date: "Monday, 27 May",
    fullAddress: "Grace Villa, Punkunnam, Thrissur",
    time: "03:30 – 04:30 PM",
    specialInstruction: "Switch off main power before working.",
    worker: {
      name: "John Doe",
      avatar: "https://randomuser.me/api/portraits/men/30.jpg",
      location: "Ernakulam",
      phone: "+91 98477 98765",
    },
    status: "cancelled",
  },
  {
    service: "Gardening",
    date: "Tuesday, 28 May",
    fullAddress: "Lakeside House, P.O Mannuthy, Thrissur",
    time: "08:00 – 09:30 AM",
    specialInstruction: "Trim the hedges near the driveway first.",
    worker: {
      name: "Anand Krish",
      avatar: "https://randomuser.me/api/portraits/men/70.jpg",
      location: "Thrissur",
      phone: "+91 94970 44332",
    },
    status: "in-progress",
  },
  {
    service: "Painting",
    date: "Wednesday, 29 May",
    fullAddress: "ABC Residency, Chembukkavu, Thrissur",
    time: "11:00 – 01:00 PM",
    specialInstruction: "Apply a second coat only after 4 hours.",
    worker: {
      name: "Maya Nair",
      avatar: "https://randomuser.me/api/portraits/women/50.jpg",
      location: "Kochi",
      phone: "+91 97452 55522",
    },
    status: "completed",
  },
  {
    service: "Carpentry",
    date: "Thursday, 30 May",
    fullAddress: "Sunrise Villa, Ollur, Thrissur",
    time: "02:00 – 03:00 PM",
    specialInstruction: "Check the wood polish shade before applying.",
    worker: {
      name: "Vijay Menon",
      avatar: "https://randomuser.me/api/portraits/men/33.jpg",
      location: "Thrissur",
      phone: "+91 95674 78821",
    },
    status: "cancelled",
  },
  {
    service: "Plumbing",
    date: "Saturday, 1 June",
    fullAddress: "Hill View Apartments, Punkunnam, Thrissur",
    time: "09:00 – 10:00 AM",
    specialInstruction: "Inspect all bathroom taps for leakage.",
    worker: {
      name: "Daison Babu",
      avatar: "https://randomuser.me/api/portraits/men/45.jpg",
      location: "Palakkad",
      phone: "+91 94435 11223",
    },
    status: "in-progress",
  },
  {
    service: "Electrical",
    date: "Sunday, 2 June",
    fullAddress: "Rosewood Villa, Westfort, Thrissur",
    time: "03:00 – 04:30 PM",
    specialInstruction: "Bring extra LED bulbs for replacement.",
    worker: {
      name: "Sreeja Raj",
      avatar: "https://randomuser.me/api/portraits/women/61.jpg",
      location: "Thrissur",
      phone: "+91 96332 66112",
    },
    status: "completed",
  },
  {
    service: "Cleaning",
    date: "Monday, 3 June",
    fullAddress: "Dream Home, P.O Kunnamkulam, Thrissur",
    time: "12:00 – 01:00 PM",
    specialInstruction: "Focus on kitchen and bathroom areas.",
    worker: {
      name: "Jane Cooper",
      avatar: "https://randomuser.me/api/portraits/women/65.jpg",
      location: "Kollam",
      phone: "+91 98764 22255",
    },
    status: "in-progress",
  },
  {
    service: "Gardening",
    date: "Tuesday, 4 June",
    fullAddress: "Palm Valley, Ayyanthole, Thrissur",
    time: "07:30 – 09:00 AM",
    specialInstruction: "Water plants before trimming.",
    worker: {
      name: "Ravi Kumar",
      avatar: "https://randomuser.me/api/portraits/men/80.jpg",
      location: "Palakkad",
      phone: "+91 95444 10033",
    },
    status: "completed",
  },
  {
    service: "Painting",
    date: "Wednesday, 5 June",
    fullAddress: "River View, P.O Ollur, Thrissur",
    time: "11:30 – 12:30 PM",
    specialInstruction: "Cover furniture before painting starts.",
    worker: {
      name: "Maya Nair",
      avatar: "https://randomuser.me/api/portraits/women/50.jpg",
      location: "Kochi",
      phone: "+91 97452 55522",
    },
    status: "cancelled",
  },
  {
    service: "Carpentry",
    date: "Thursday, 6 June",
    fullAddress: "Lake View, Mannuthy, Thrissur",
    time: "01:00 – 02:30 PM",
    specialInstruction: "Install new hinges for the kitchen cabinets.",
    worker: {
      name: "Vijay Menon",
      avatar: "https://randomuser.me/api/portraits/men/33.jpg",
      location: "Thrissur",
      phone: "+91 95674 78821",
    },
    status: "in-progress",
  },
  {
    service: "Plumbing",
    date: "Friday, 7 June",
    fullAddress: "Dream Castle, Koorkanchery, Thrissur",
    time: "09:30 – 10:30 AM",
    specialInstruction: "Check underground pipeline connection.",
    worker: {
      name: "John Mathew",
      avatar: "https://randomuser.me/api/portraits/men/48.jpg",
      location: "Ernakulam",
      phone: "+91 98470 55441",
    },
    status: "completed",
  },
  {
    service: "Cleaning",
    date: "Saturday, 8 June",
    fullAddress: "Rose Villa, P.O Ollur, Thrissur",
    time: "02:00 – 03:30 PM",
    specialInstruction: "Focus on balcony and living room dusting.",
    worker: {
      name: "Jane Cooper",
      avatar: "https://randomuser.me/api/portraits/women/65.jpg",
      location: "Kollam",
      phone: "+91 98764 22255",
    },
    status: "cancelled",
  },
  {
    service: "Electrical",
    date: "Sunday, 9 June",
    fullAddress: "Sunshine Apartments, East Fort, Thrissur",
    time: "04:00 – 05:00 PM",
    specialInstruction: "Inspect main switchboard for any loose wires.",
    worker: {
      name: "John Doe",
      avatar: "https://randomuser.me/api/portraits/men/30.jpg",
      location: "Ernakulam",
      phone: "+91 98477 98765",
    },
    status: "in-progress",
  },
];
